// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function LaunchLLM(arg1) {
  return window['go']['main']['App']['LaunchLLM'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShutdownLLM() {
  return window['go']['main']['App']['ShutdownLLM']();
}
