// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteChatSession(arg1:number):Promise<void>;

export function GetModels():Promise<Array<string>>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetPrompts():Promise<Array<string>>;

export function HandleChat(arg1:number,arg2:string):Promise<void>;

export function HealthCheck():Promise<string>;

export function LaunchLLM(arg1:string):Promise<string>;

export function LoadChatHistory(arg1:number):Promise<Array<main.ChatMessage>>;

export function LoadChatSessions():Promise<Array<main.ChatSession>>;

export function LoadSettings():Promise<string>;

export function NewChat(arg1:string):Promise<number>;

export function SaveSettings(arg1:string):Promise<void>;

export function ShutdownLLM():Promise<void>;

export function StopStream(arg1:number):Promise<void>;
