// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function HandleChat(arg1, arg2) {
  return window['go']['main']['App']['HandleChat'](arg1, arg2);
}

export function LaunchLLM(arg1) {
  return window['go']['main']['App']['LaunchLLM'](arg1);
}

export function LoadChatHistory(arg1) {
  return window['go']['main']['App']['LoadChatHistory'](arg1);
}

export function LoadChatSessions() {
  return window['go']['main']['App']['LoadChatSessions']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function NewChat() {
  return window['go']['main']['App']['NewChat']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}
