// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels():Promise<Array<string>>;

export function LaunchLLM(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function NewChat():Promise<number>;

export function SaveSettings(arg1:string):Promise<void>;

export function ShutdownLLM():Promise<void>;
