// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddArtifact(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddArtifact'](arg1, arg2, arg3, arg4);
}

export function DeleteArtifact(arg1) {
  return window['go']['main']['App']['DeleteArtifact'](arg1);
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetPrompts() {
  return window['go']['main']['App']['GetPrompts']();
}

export function HandleChat(arg1, arg2) {
  return window['go']['main']['App']['HandleChat'](arg1, arg2);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function IsLLMLoaded() {
  return window['go']['main']['App']['IsLLMLoaded']();
}

export function LaunchLLM(arg1) {
  return window['go']['main']['App']['LaunchLLM'](arg1);
}

export function ListArtifacts(arg1) {
  return window['go']['main']['App']['ListArtifacts'](arg1);
}

export function LoadChatHistory(arg1) {
  return window['go']['main']['App']['LoadChatHistory'](arg1);
}

export function LoadChatSessions() {
  return window['go']['main']['App']['LoadChatSessions']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function NewChat(arg1) {
  return window['go']['main']['App']['NewChat'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShutdownLLM() {
  return window['go']['main']['App']['ShutdownLLM']();
}

export function StopStream(arg1) {
  return window['go']['main']['App']['StopStream'](arg1);
}

export function UpdateChatSystemPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateChatSystemPrompt'](arg1, arg2);
}
