name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libglib2.0-dev \
            libgio2.0-dev \
            libsoup3.0-dev \
            pkg-config

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build application
        run: |
          cd local-llm-chat
          wails build -tags webkit2_41 -o local-llm-chat-linux

      - name: Prepare release assets
        run: |
          cd local-llm-chat/build/bin
          mkdir release
          mv local-llm-chat-linux release/
          cp -r ../../prompts release/
          cp ../../mcp.json release/
          cd release
          tar -czvf ../../../../local-llm-chat-linux.tar.gz .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./local-llm-chat-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build application
        run: |
          cd local-llm-chat
          wails build -o local-llm-chat-windows.exe

      - name: Prepare release assets
        run: |
          cd local-llm-chat/build/bin
          mkdir release
          move local-llm-chat-windows.exe release/
          robocopy ..\..\prompts release\prompts /E
          copy ..\..\mcp.json release\mcp.json
          cd release
          powershell -Command "Compress-Archive -Path * -DestinationPath ..\..\..\..\local-llm-chat-windows.zip"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./local-llm-chat-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build application
        run: |
          cd local-llm-chat
          wails build -o "local-llm-chat"

      - name: Prepare release assets
        run: |
          cd local-llm-chat/build/bin
          mkdir release
          mv "local-llm-chat.app" release/
          cp -r ../../prompts release/
          cp ../../mcp.json release/
          cd release
          zip -r ../../../../local-llm-chat-macos.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./local-llm-chat-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
